# File to define common network table constants

# Information generated by computer vision
class VisionTable:
  name       = "Vision Processing Table"
  bot_x_pose = "Bot X"
  bot_y_pose = "Bot Y"
  bot_r_pose = "Bot R"
  bot_pose = "Bot Pose"
  tag_pose = "Tag Pose"

class SimTable:
  name = "Simulator Controller Table"
  x    = "Sim X Command"
  y    = "Sim Y Command"
  r    = "Sim R Command"
