repos:
  # Ruff pre-commit hooks.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.13
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
        args: ["--check"]
