# This file describes the Continuous Integration (CI) steps. It will run a series of tests on every GitLab Pull Request (PR)

name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  lint_and_format_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Lint
        run: ruff check --output-format=github .
      - name: Check Formatting
        run: ruff format --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: TODO
        run: |
          echo "test"
